apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: fint-flyt-configuration-service
    path: readiness-probe-deployment-patch.yaml
