apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-configuration-service
spec:
  readiness:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 6
